[build]
  base = "/"
  command = "npm run build"
  publish = "build"
  
# Production settings
[build.environment]
  NODE_ENV = "production"

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

